feat: 多语言插件支持beta版本
Tencent/feflow pull request #385
Opened 2022-01-25 08:35 UTC by codetker

cli、npm包、多语言插件发 beta/alpha 版本的标准：
1、由于项目中使用 semver.gt 来判断版本更新，因此根据其规则：如果当前线上版本为 a.b.c，那么 beta/alpha 需要是 a.b.c-betaxxx 或者 a.b.c-alphaxxx
2、可以发布比 a.b.c 低的 beta/alpha 版本，但是不允许发布比 a.b.c 更高的版本，防止自动更新默认更新到了

2022-01-26 03:09 UTC, xqxian commented on packages/feflow-cli/src/core/universal-pkg/dep/version.ts
> +    // return /^v(0|[1-9]\d*).(0|[1-9]\d*).(0|[1-9]\d*)$/i.test(version);
注释掉的代码应直接删除，后续有需要可通过 git 找回

2022-02-28 04:02 UTC, codetker commented on packages/feflow-cli/src/core/universal-pkg/dep/version.ts
> +    // return /^v(0|[1-9]\d*).(0|[1-9]\d*).(0|[1-9]\d*)$/i.test(version);
fixed

2022-02-28 04:03 UTC, codetker commented
feat: 所有包在安装时，先获取所有的 tag 列表，再筛选满足条件的最大 tag 并返回

2022-02-28 10:25 UTC, xqxian requested changes

2022-02-28 10:25 UTC, xqxian commented on packages/feflow-cli/src/core/universal-pkg/repository/git.ts
> +export async function getExitsTag(repoUrl: string, pluginVersion: string): Promise<string | undefined> {
该函数与 `getTag` 很多代码类似，应尽量复用

2022-03-01 04:24 UTC, codetker commented on packages/feflow-cli/src/core/universal-pkg/repository/git.ts
> +export async function getBetaTag(repoUrl: string, pluginVersion: string): Promise<string | undefined> {
已合并为同一个方法

2022-03-01 04:24 UTC, codetker commented on packages/feflow-cli/src/core/native/install.ts
> +        if (pluginVersion === 'beta' || pluginVersion === 'alpha' || pluginVersion === 'next') {
fixed。现在先取所有的版本号，再判断

2022-03-01 04:25 UTC, codetker commented on packages/feflow-cli/src/shared/package-json.ts
> +        versionList.forEach((tag: string) => {
这里要拿符合条件中最大的版本号，find 不大好写

2022-03-01 04:25 UTC, codetker commented on packages/feflow-cli/src/shared/package-json.ts
>      .then((response: AxiosResponse) => {
已修改成一致，并检查所有的调用

2022-03-01 04:26 UTC, codetker commented on packages/feflow-cli/src/core/universal-pkg/repository/git.ts
> +  for (const tagStr of tagList) {
已改成 forEach，保持和 npm 那边一致

2022-03-01 04:26 UTC, codetker commented on packages/feflow-cli/src/core/universal-pkg/repository/git.ts
> +export async function getExitsTag(repoUrl: string, pluginVersion: string): Promise<string | undefined> {
已合并

2022-03-07 15:30 UTC, xqxian approved these changes

2022-03-07 15:32 UTC, merged